
use_frameworks! :linkage => :static

platform :ios, '10.0'

target 'ERCCollection' do
	pod 'SnapKit'
	pod 'MJRefresh'
	pod 'Moya'
	pod 'Alamofire', '4.9.1'
	pod 'RxSwift'
	pod 'RxDataSources'
	pod 'Kingfisher'
	pod 'SVGKit'
	pod 'SDWebImageAVIFCoder'
	pod 'libavif', :subspecs => [
	  'libdav1d',
	  'librav1e'
	]
end

